[package]
name = "korvo-media-host-tests"
version = "0.1.0"
edition = "2024"
publish = false
[dependencies]
embedded-sdmmc = { path = "../../vendor/embedded-sdmmc", default-features = false }
nanomp3-core = {version="0.2",default-features=false}
jpeg-encoder = { version = "0.7.1", default-features = false }

zune-jpeg = { version = "0.5.15", default-features = false }

heapless = "0.8"

embassy-usb-host = {path="/home/nws/w/esp32/embassy-usb-host/embassy-usb-host"}
