#!/usr/bin/env python3
"""Generate Q15 Blackman-windowed sinc coefficients; no runtime tool dependency."""
import math
from pathlib import Path
TAPS, PHASES = 64, 64

def row(phase, cutoff=0.47):
    values = []
    for tap in range(TAPS):
        x = tap - (31 + phase / PHASES)
        window = 0.42 + 0.5 * math.cos(math.pi * x / 32) + 0.08 * math.cos(2 * math.pi * x / 32)
        sinc = 2 * cutoff if x == 0 else math.sin(2 * math.pi * cutoff * x) / (math.pi * x)
        values.append(sinc * window)
    total = sum(values)
    q = [round(v / total * 32768) for v in values]
    q[31] += 32768 - sum(q)
    return q

path = Path(__file__).resolve().parents[1] / 'src/resampler_coeffs.rs'
with path.open('w') as out:
    out.write('// Generated by scripts/generate-resampler.py. 64 taps, 64 phases, Q15.\n')
    out.write('#[rustfmt::skip]\n')
    out.write('pub const COEFFICIENTS: [[i16; 64]; 65] = [\n')
    for phase in range(PHASES + 1):
        out.write('    [' + ', '.join(map(str, row(phase))) + '],\n')
    out.write('];\n')
